name: ✨ Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🚀
        Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: 📋 Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature in a few sentences...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 📦 Component
      description: Which part of the platform would this feature affect?
      options:
        - Web Application
        - Embeddable Widget
        - Documentation
        - API/Backend
        - Database
        - Authentication
        - Admin Dashboard
        - Analytics
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is.
        Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: |
        A clear and concise description of what you want to happen.
        Include any specific implementation details if you have them.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        A clear and concise description of any alternative solutions 
        or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for our use case
        - Critical - Blocking our adoption
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: 👤 User Type
      description: What type of user would benefit from this feature?
      options:
        - End Users (chatbot visitors)
        - Chatbot Builders
        - Developers/Integrators
        - Administrators
        - All Users
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples of similar features.
      placeholder: |
        Attach or link to any visual examples, mockups, or references 
        that help illustrate the feature.

  - type: textarea
    id: additional
    attributes:
      label: 📝 Additional Context
      description: Add any other context, screenshots, or examples about the feature request.

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I understand this is a request and not a guarantee of implementation
          required: true
        - label: I am willing to help with testing/feedback during development
          required: false